spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/optiplant}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# Seeds habilitados en local para facilitar pruebas
app.seed.catalog.enabled=true
app.seed.inventory.enabled=true
app.seed.sales-history.enabled=true

