spring.application.name=backend


spring.datasource.url=jdbc:postgresql://ep-withered-brook-aco0icvr-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_4vbinkjRthU6
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Tiempo maximo para cambios/devoluciones desde la fecha de venta
app.returns.max-hours=72

# Siembra inicial de categorias/productos para ambiente local
app.seed.catalog.enabled=true

# Siembra inicial de inventario por sucursal
app.seed.inventory.enabled=true

